status: ZAGLUSHKA
zamenit_na: заменить реестром дорог региона
istochnik: 'ПП РФ 1931, место происшествия. ЗАГЛУШКА: заменить реестром дорог региона'
items:
- kod: R354
  nazvanie: Р-354 Екатеринбург — Шадринск — Курган
- kod: R351
  nazvanie: Р-351 Екатеринбург — Тюмень
- kod: R242
  nazvanie: Р-242 Пермь — Екатеринбург
- kod: E22
  nazvanie: Е-22 Екатеринбург — Серов
- kod: M5
  nazvanie: М-5 «Урал»
- kod: INAYA
  nazvanie: Иная дорога
