status: ZAGLUSHKA
zamenit_na: заменить справочником объектов региона
istochnik: 'ОКПО. ЗАГЛУШКА: заменить справочником объектов региона'
items:
- kod: ZHILOY
  nazvanie: Жилой дом
- kod: SHKOLA
  nazvanie: Школа
- kod: DETSAD
  nazvanie: Детский сад
- kod: BOLNICA
  nazvanie: Медицинская организация
- kod: TC
  nazvanie: Торговый центр
- kod: VOKZAL
  nazvanie: Вокзал
- kod: PROMYSHLENNY
  nazvanie: Промышленный объект
- kod: ENERGETIKA
  nazvanie: Объект энергетики
- kod: TRANSPORT
  nazvanie: Объект транспорта
- kod: INOE
  nazvanie: Иной объект
