istochnik: 'ПП РФ 1931, спец.часть СМП: кто вызвал'
items:
- kod: SAM
  nazvanie: Сам больной
- kod: SUPRUG
  nazvanie: Супруг, супруга
- kod: RODITEL
  nazvanie: Родитель
- kod: REBENOK
  nazvanie: Сын, дочь
- kod: RODSTVENNIK
  nazvanie: Иной родственник
- kod: SOSED
  nazvanie: Сосед
- kod: PROHOZHY
  nazvanie: Прохожий
- kod: KOLLEGA
  nazvanie: Коллега
- kod: SOTRUDNIK
  nazvanie: Сотрудник организации
- kod: INOE
  nazvanie: Иное
