istochnik: ПП РФ 1931, описание подозреваемых
items:
- kod: HUDOSHCHAVOE
  nazvanie: Худощавое
- kod: SREDNEE
  nazvanie: Среднее
- kod: PLOTNOE
  nazvanie: Плотное
- kod: POLNOE
  nazvanie: Полное
- kod: SPORTIVNOE
  nazvanie: Спортивное
- kod: NEIZV
  nazvanie: Не определено
