istochnik: ПП РФ 1931, транспортные средства
items:
- kod: LEGKOVOY
  nazvanie: Легковой автомобиль
- kod: GRUZOVOY
  nazvanie: Грузовой автомобиль
- kod: AVTOBUS
  nazvanie: Автобус
- kod: MIKROAVTOBUS
  nazvanie: Микроавтобус
- kod: MOTOCIKL
  nazvanie: Мотоцикл
- kod: VELOSIPED
  nazvanie: Велосипед
- kod: SPECTEHNIKA
  nazvanie: Спецтехника
- kod: PRICEP
  nazvanie: Прицеп
- kod: INOE
  nazvanie: Иное
