istochnik: ПП РФ 1931, спец.часть газовой сети
items:
- kod: ZAPAH
  nazvanie: Запах газа
- kod: UTECHKA_KVARTIRA
  nazvanie: Утечка в помещении
- kod: UTECHKA_PODEZD
  nazvanie: Утечка в подъезде
- kod: POVREZHDENIE
  nazvanie: Повреждение газопровода
- kod: ZEMLYANYE
  nazvanie: Повреждение при земляных работах
- kod: NEISPRAVNOST
  nazvanie: Неисправность оборудования
- kod: OTRAVLENIE
  nazvanie: Отравление газом
- kod: INOE
  nazvanie: Иное
