istochnik: ПП РФ 1931, спец.часть «Антитеррор»
items:
- kod: UGROZA_VZRYVA
  nazvanie: Сообщение об угрозе взрыва
- kod: PODOZR_PREDMET
  nazvanie: Подозрительный предмет
- kod: VZRYV
  nazvanie: Взрыв
- kod: ZAHVAT_ZALOZHNIKOV
  nazvanie: Захват заложников
- kod: VOORUZH_NAPADENIE
  nazvanie: Вооружённое нападение
- kod: ZAHVAT_OBEKTA
  nazvanie: Захват объекта
- kod: INOE
  nazvanie: Иное
