istochnik: ПП РФ 1931, спец.часть пожарной охраны
items:
- kod: ZDANIE
  nazvanie: Пожар в здании
- kod: KVARTIRA
  nazvanie: Пожар в квартире
- kod: CHASTNY_DOM
  nazvanie: Пожар в частном доме
- kod: TS
  nazvanie: Загорание транспортного средства
- kod: LES
  nazvanie: Лесной или ландшафтный пожар
- kod: MUSOR
  nazvanie: Горение мусора
- kod: ELEKTRO
  nazvanie: Замыкание, горение электрооборудования
- kod: ZADYMLENIE
  nazvanie: Задымление без открытого огня
- kod: VZRYV
  nazvanie: Взрыв
- kod: INOE
  nazvanie: Иное
