istochnik: ПП РФ 1931, спец.часть полиции
items:
- kod: KRAZHA
  nazvanie: Кража
- kod: GRABEZH
  nazvanie: Грабёж
- kod: RAZBOJ
  nazvanie: Разбой
- kod: DRAKA
  nazvanie: Драка
- kod: HULIGANSTVO
  nazvanie: Хулиганство
- kod: UGON
  nazvanie: Угон транспортного средства
- kod: MOSHENNICHESTVO
  nazvanie: Мошенничество
- kod: PROPAL
  nazvanie: Безвестное исчезновение
- kod: SEMEYNY
  nazvanie: Семейно-бытовой конфликт
- kod: NARKOTIKI
  nazvanie: Незаконный оборот наркотиков
- kod: OSKORBLENIE
  nazvanie: Оскорбление, угрозы
- kod: INOE
  nazvanie: Иное
